repos:
  - repo: local
    hooks:
      - id: dart-format
        language: system
        name: Format Dart Code
        entry: dart format --output write --set-exit-if-changed
        files: lib/|test/
      - id: flutter-analyze
        language: system
        name: Analyze Flutter Code
        entry: flutter analyze
        files: lib/|test/
