on: push
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - name: Download dependencies
      run: flutter pub get
    - name: Analyze code
      run: flutter analyze
    - name: Run tests
      run: flutter test --coverage --reporter expanded
    - name: Upload coverage to codecov
      run: curl -s https://codecov.io/bash
      shell: bash
