on: push
name: Tests
jobs:
  test:
    name: Set up project and run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.27.1'
    - name: Download dependencies
      run: flutter pub get
    - name: Analyze code
      run: flutter analyze
    - name: Verify if code is formatted properly
      run: dart format -o show --set-exit-if-changed .
    - name: Run tests
      run: flutter test --coverage --reporter expanded
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage/lcov.info
        fail_ci_if_error: true
        verbose: true
